### ISSUE TITLE
Could you please share the data tmall.npy and patent.npy?Cause I cannot successfully send you an email,so if there is another way to acquire the data.

### ISSUE THREAD

**Issue by yexinruyexinru** [EdisonLeeeee/SpikeNet#4]

**Comment by EdisonLeeeee** [comment]
The datasets for Tmall and Patent have been shared through Aliyun Drive, and the link is as follows: https://www.aliyundrive.com/s/LH9qa9XZmXa. 

Note: Since Aliyun Drive does not support direct sharing of npy files, you will need to manually change the file extension to .npy after downloading. Sorry for any inconvenience.

Bests,
Jintang
